apiVersion: batch/v1
kind: CronJob
metadata:
  name: create-year-cronjob
spec:
  schedule: "0 3 * 1 *" # 3 AM on 1st of January
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      template:
        spec:
          containers:
          - name: create-year-cronjob
            image: odprti-racuni
            command:
              - python
              - manage.py
              - create_financial_year
            env:
              - name: DJANGO_SETTINGS_MODULE
                value: odprti_racuni.settings
            envFrom:
              - secretRef:
                name: odprti-racuni-credentials

          restartPolicy: Never
