apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odprti-racuni
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

images:
  - name: odprti-racuni
    newName: rg.fr-par.scw.cloud/djnd/odprti-racuni
    newTag: 'a88a8dbdfec8af8545ad4179fc0c1d3a1892e5ce'
