apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: odprti-racuni
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml

images:
  - name: odprti-racuni
    newName: rg.fr-par.scw.cloud/djnd/odprti-racuni
    newTag: 'f73d88b595492f2a2b47f507d60c6ed2cfaded4c'
