# Generated by Django 4.0.5 on 2022-07-01 16:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('start_time', models.DateField()),
                ('end_time', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('logo', models.ImageField(upload_to='')),
                ('address', models.TextField()),
                ('city', models.TextField()),
                ('post_number', models.TextField()),
                ('tax_number', models.CharField(max_length=10)),
                ('registration_number', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('trr', models.TextField()),
                ('is_charity', models.BooleanField(default=False)),
                ('is_for_the_public_good', models.TextField(blank=True, default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time_employees', models.IntegerField(default=0)),
                ('other_employees', models.IntegerField(default=0)),
                ('volunteers', models.IntegerField(default=0)),
                ('members', models.IntegerField(default=0)),
                ('employees_by_hours', models.IntegerField(default=0)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.organization')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('average_gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('job_share', models.IntegerField(default=100, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.organization')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.financialyear')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.documentcategory')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.organization')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='nvo.financialyear')),
            ],
        ),
    ]
