# Generated by Django 4.0.5 on 2022-08-16 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("nvo", "0008_organization_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Finance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount_voluntary_work",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Amount of voluntary work",
                    ),
                ),
                (
                    "payments_project_partners",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Payments to projects partners",
                    ),
                ),
                (
                    "payment_state_budget",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Payment to the state budget",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to="nvo.organization",
                        verbose_name="Organiaztion",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)s_related",
                        to="nvo.financialyear",
                        verbose_name="Year",
                    ),
                ),
            ],
        ),
    ]
