# Generated by Django 4.0.5 on 2022-08-16 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nvo", "0009_finance"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="difference_payment_state_budget",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Difference payment state budget",
            ),
        ),
    ]
