# Generated by Django 4.0.5 on 2022-12-19 16:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvo', '0019_alter_infotext_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='organization_share',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Organization share'),
        ),
        migrations.AlterField(
            model_name='project',
            name='self_money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Self money'),
        ),
        migrations.AlterField(
            model_name='project',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total value'),
        ),
    ]
