# Generated by Django 4.0.5 on 2022-12-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvo', '0020_alter_project_organization_share_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donations',
            name='organization_donations_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Organization donations amount'),
        ),
        migrations.AlterField(
            model_name='donations',
            name='personal_donations_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Personal donation amount'),
        ),
    ]
