# Generated by Django 4.0.5 on 2023-01-04 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nvo', '0021_alter_donations_organization_donations_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationfinancialyear',
            name='embed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='financial_year_through', to='nvo.embed', verbose_name='Embed'),
        ),
    ]
