# Generated by Django 4.0.5 on 2023-03-10 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nvo', '0025_paymentratio_highest_absolute_salary_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentratio',
            name='highest_absolute_salary',
            field=models.FloatField(default=1, verbose_name='Highest absolute salary'),
        ),
        migrations.AlterField(
            model_name='paymentratio',
            name='highest_salary',
            field=models.FloatField(default=1, verbose_name='Highest salary'),
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
