# Generated by Django 4.0.5 on 2023-04-11 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nvo", "0027_alter_donations_options_alter_finance_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentratio",
            name="highest_absolute_salary",
            field=models.FloatField(null=True, verbose_name="Highest absolute salary"),
        ),
        migrations.AlterField(
            model_name="paymentratio",
            name="highest_salary",
            field=models.FloatField(null=True, verbose_name="Highest salary"),
        ),
    ]
