# Generated by Django 4.0.5 on 2023-04-12 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("nvo", "0028_alter_paymentratio_highest_absolute_salary_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paymentratio",
            name="highest_absolute_salary",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Highest absolute salary"
            ),
        ),
        migrations.AlterField(
            model_name="paymentratio",
            name="highest_salary",
            field=models.FloatField(
                blank=True, null=True, verbose_name="Highest salary"
            ),
        ),
    ]
